//
//  VideoIncomingCallProtocols.swift
//  Sami
//
//  Created Kencor Health on 30/01/19.
//  Copyright © 2019 Kencor Health. All rights reserved .
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VideoIncomingCallWireframeProtocol: class {

}
//MARK: Presenter -
protocol VideoIncomingCallPresenterProtocol: class {

    var interactor: VideoIncomingCallInteractorInputProtocol? { get set }
    func screenWillDisappear()
    
    func callRejected()
    func callAccepted()
    
    func getMessageObject()->VideoCallMessage?
}

//MARK: Interactor -
protocol VideoIncomingCallInteractorOutputProtocol: class {
}

protocol VideoIncomingCallInteractorInputProtocol: class {

    var presenter: VideoIncomingCallInteractorOutputProtocol?  { get set }
    func callRejected()
    func callAccepted()
    func getMessageObject()->VideoCallMessage
}

//MARK: View -
protocol VideoIncomingCallViewProtocol: class {

    var presenter: VideoIncomingCallPresenterProtocol?  { get set }
    
    
}
