//
//  VideoIncomingCallRouter.swift
//  Sami
//
//  Created Kencor Health on 30/01/19.
//  Copyright © 2019 Kencor Health. All rights reserved .
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VideoIncomingCallRouter: VideoIncomingCallWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(objVideoCallMessage:VideoCallMessage, completionHandler:@escaping (Bool)->()) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        
        let view            = UIStoryboard.init(name: "VideoIncomingCallStoryboard", bundle: nil).instantiateViewController(withIdentifier: "VideoIncomingCallViewController") as! VideoIncomingCallViewController
        let interactor      = VideoIncomingCallInteractor.init(videoCallMessage: objVideoCallMessage, completionHandler: completionHandler)
        let router          = VideoIncomingCallRouter()
        let presenter       = VideoIncomingCallPresenter.init(interface: view, interactor: interactor, router: router)
        
        view.presenter              = presenter
        interactor.presenter        = presenter
        router.viewController       = view

        return view
    }
    
    deinit {
        print("Deinit \(self)")
    }
}
